### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by wangyongjie-ntu** [vbranders/mssm#2]
Hi Branders, 
 
I meet such error during running, Could you help work it out? 

Error in new(mssm.jInst("CPGC"), javaMatrix, budget, as.integer(convergence),  : 
  no slot of name "virtual" for this object of class "jclassName"

Here is the config info of run "R CMD javareconf -e"

Java interpreter : /usr/bin/java
Java version     : 11.0.8
Java home path   : /usr/lib/jvm/java-11-openjdk-amd64
Java compiler    : /usr/bin/javac
Java headers gen.: 
Java archive tool: /usr/bin/jar

trying to compile and link a JNI program 
detected JNI cpp flags    : -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux
detected JNI linker flags : -L/usr/lib/jvm/java-11-openjdk-amd64/lib/server -ljvm
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-AitvI6/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c conftest.c -o conftest.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o conftest.so conftest.o -L/usr/lib/jvm/java-11-openjdk-amd64/lib/server -ljvm -L/usr/lib/R/lib -lR

The following Java variables have been exported:
JAVA_HOME JAVA JAVAC JAVAH JAR JAVA_LIBS JAVA_CPPFLAGS JAVA_LD_LIBRARY_PATH

Thanks.
Yongjie

**Comment by vbranders** [comment]
Hi Yongjie,

Thanks for spotting the issue.
It has been fixed.

Warm regards,
Vincent
